[2024-09-10T02:53:15.128+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-10T02:53:15.132+0800] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: casia-hwdb_elt.download_casia-hwdb_1 manual__2024-09-09T18:23:36.002239+00:00 [queued]>
[2024-09-10T02:53:15.134+0800] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: casia-hwdb_elt.download_casia-hwdb_1 manual__2024-09-09T18:23:36.002239+00:00 [queued]>
[2024-09-10T02:53:15.134+0800] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2024-09-10T02:53:15.138+0800] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): download_casia-hwdb_1> on 2024-09-09 18:23:36.002239+00:00
[2024-09-10T02:53:15.145+0800] {logging_mixin.py:190} WARNING - /Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=73053) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-10T02:53:15.145+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'casia-hwdb_elt', 'download_casia-hwdb_1', 'manual__2024-09-09T18:23:36.002239+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/var/folders/3n/sh024_795c590k086c59jsw00000gn/T/tmpb7dgub4y']
[2024-09-10T02:53:15.146+0800] {standard_task_runner.py:72} INFO - Started process 73142 to run task
[2024-09-10T02:53:15.146+0800] {standard_task_runner.py:105} INFO - Job 57: Subtask download_casia-hwdb_1
[2024-09-10T02:53:15.161+0800] {task_command.py:467} INFO - Running <TaskInstance: casia-hwdb_elt.download_casia-hwdb_1 manual__2024-09-09T18:23:36.002239+00:00 [running]> on host chens-macbook-pro.local
[2024-09-10T02:53:15.182+0800] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='casia-hwdb_elt' AIRFLOW_CTX_TASK_ID='download_casia-hwdb_1' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T18:23:36.002239+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-09T18:23:36.002239+00:00'
[2024-09-10T02:53:15.183+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-10T02:53:15.183+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-10T02:53:15.183+0800] {logging_mixin.py:190} INFO - Current task name:download_casia-hwdb_1 state:running start_date:2024-09-09 18:53:15.132586+00:00
[2024-09-10T02:53:15.183+0800] {logging_mixin.py:190} INFO - Dag name:casia-hwdb_elt and current dag run status:running
[2024-09-10T02:53:15.183+0800] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-10T02:53:15.246+0800] {s3.py:36} ERROR - Error checking s3://if-letters-home-could-sing/data/casia-hwdb_1.zip: An error occurred (403) when calling the HeadObject operation: Forbidden
[2024-09-10T02:53:15.249+0800] {baseoperator.py:405} WARNING - DownloadOperator.execute cannot be called outside TaskInstance!
[2024-09-10T02:53:15.387+0800] {logging_mixin.py:190} INFO - Error updating job state: An error occurred (UnrecognizedClientException) when calling the UpdateItem operation: The security token included in the request is invalid.
[2024-09-10T02:53:15.400+0800] {s3.py:36} ERROR - Error checking s3://if-letters-home-could-sing/data/casia-hwdb_1.zip: An error occurred (403) when calling the HeadObject operation: Forbidden
[2024-09-10T03:10:30.377+0800] {job.py:229} INFO - Heartbeat recovered after 1025.19 seconds
[2024-09-10T03:27:41.093+0800] {job.py:229} INFO - Heartbeat recovered after 1030.72 seconds
[2024-09-10T03:45:34.730+0800] {job.py:229} INFO - Heartbeat recovered after 1073.64 seconds
[2024-09-10T04:00:59.396+0800] {job.py:229} INFO - Heartbeat recovered after 924.67 seconds
[2024-09-10T04:18:33.025+0800] {job.py:229} INFO - Heartbeat recovered after 1053.63 seconds
[2024-09-10T04:35:25.643+0800] {job.py:229} INFO - Heartbeat recovered after 1012.62 seconds
[2024-09-10T04:53:09.257+0800] {job.py:229} INFO - Heartbeat recovered after 1063.62 seconds
[2024-09-10T04:54:20.850+0800] {job.py:229} INFO - Heartbeat recovered after 71.60 seconds
[2024-09-10T05:09:54.677+0800] {job.py:229} INFO - Heartbeat recovered after 928.78 seconds
[2024-09-10T05:27:28.371+0800] {job.py:229} INFO - Heartbeat recovered after 1053.70 seconds
[2024-09-10T05:35:58.967+0800] {job.py:229} INFO - Heartbeat recovered after 510.60 seconds
[2024-09-10T05:50:03.155+0800] {job.py:229} INFO - Heartbeat recovered after 839.14 seconds
[2024-09-10T05:55:20.827+0800] {job.py:229} INFO - Heartbeat recovered after 317.68 seconds
[2024-09-10T06:11:35.107+0800] {job.py:229} INFO - Heartbeat recovered after 969.27 seconds
[2024-09-10T06:28:42.788+0800] {job.py:229} INFO - Heartbeat recovered after 1027.68 seconds
[2024-09-10T06:45:29.435+0800] {job.py:229} INFO - Heartbeat recovered after 1006.65 seconds
[2024-09-10T06:56:22.013+0800] {job.py:229} INFO - Heartbeat recovered after 652.58 seconds
[2024-09-10T06:58:06.514+0800] {job.py:229} INFO - Heartbeat recovered after 99.48 seconds
[2024-09-10T07:15:07.920+0800] {job.py:229} INFO - Heartbeat recovered after 1021.41 seconds
[2024-09-10T07:32:02.554+0800] {job.py:229} INFO - Heartbeat recovered after 1014.64 seconds
[2024-09-10T07:49:33.131+0800] {job.py:229} INFO - Heartbeat recovered after 1050.58 seconds
[2024-09-10T07:57:20.761+0800] {job.py:229} INFO - Heartbeat recovered after 467.63 seconds
[2024-09-10T08:13:26.094+0800] {job.py:229} INFO - Heartbeat recovered after 960.31 seconds
[2024-09-10T08:20:46.679+0800] {job.py:229} INFO - Heartbeat recovered after 440.59 seconds
[2024-09-10T08:36:43.391+0800] {job.py:229} INFO - Heartbeat recovered after 916.44 seconds
[2024-09-10T08:53:23.003+0800] {job.py:229} INFO - Heartbeat recovered after 999.61 seconds
[2024-09-10T08:58:20.574+0800] {job.py:229} INFO - Heartbeat recovered after 297.57 seconds
[2024-09-10T09:14:24.507+0800] {job.py:229} INFO - Heartbeat recovered after 958.92 seconds
[2024-09-10T09:42:39.804+0800] {job.py:229} INFO - Heartbeat recovered after 104.56 seconds
[2024-09-10T10:01:19.471+0800] {job.py:229} INFO - Heartbeat recovered after 384.78 seconds
[2024-09-10T10:26:54.542+0800] {job.py:229} INFO - Heartbeat recovered after 317.22 seconds
[2024-09-10T10:32:45.972+0800] {job.py:229} INFO - Heartbeat recovered after 331.30 seconds
[2024-09-10T10:33:13.311+0800] {job.py:229} INFO - Heartbeat recovered after 17.26 seconds
[2024-09-10T10:35:27.258+0800] {job.py:229} INFO - Heartbeat recovered after 118.88 seconds
[2024-09-10T10:37:19.114+0800] {job.py:229} INFO - Heartbeat recovered after 101.80 seconds
[2024-09-10T10:38:46.337+0800] {job.py:229} INFO - Heartbeat recovered after 87.23 seconds
[2024-09-10T10:40:27.696+0800] {job.py:229} INFO - Heartbeat recovered after 96.34 seconds
[2024-09-10T10:40:56.539+0800] {job.py:229} INFO - Heartbeat recovered after 18.80 seconds
[2024-09-10T10:57:48.590+0800] {job.py:229} INFO - Heartbeat recovered after 1012.05 seconds
[2024-09-10T11:01:02.764+0800] {job.py:229} INFO - Heartbeat recovered after 189.13 seconds
[2024-09-10T11:57:00.517+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-10T11:57:00.545+0800] {process_utils.py:132} INFO - Sending 15 to group 73142. PIDs of all processes in the group: [73142]
[2024-09-10T11:57:00.545+0800] {process_utils.py:87} INFO - Sending the signal 15 to group 73142
[2024-09-10T11:57:00.546+0800] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-10T11:57:00.558+0800] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/code/erniesg/if-letters-home-could-sing/pipeline/dags/elt.py", line 51, in process_download
    result = download_op.execute(kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/code/erniesg/if-letters-home-could-sing/pipeline/operators/download.py", line 36, in execute
    self.download_from_url()
  File "/Users/erniesg/code/erniesg/if-letters-home-could-sing/pipeline/operators/download.py", line 53, in download_from_url
    response = requests.get(self.source['path'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/requests/sessions.py", line 746, in send
    r.content
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/requests/models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/urllib3/response.py", line 1060, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/urllib3/response.py", line 949, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/urllib3/response.py", line 873, in _raw_read
    data = self._fp_read(amt, read1=read1) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/urllib3/response.py", line 856, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/lib/python3.12/http/client.py", line 479, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/lib/python3.12/ssl.py", line 1252, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/lib/python3.12/ssl.py", line 1104, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-09-10T11:57:00.575+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-10T11:57:00.576+0800] {logging_mixin.py:190} INFO - Task start:2024-09-09 18:53:15.132586+00:00 end:2024-09-10 03:57:00.574964+00:00 duration:32625.442378
[2024-09-10T11:57:00.576+0800] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): download_casia-hwdb_1> dag:<DAG: casia-hwdb_elt> dagrun:<DagRun casia-hwdb_elt @ 2024-09-09 18:23:36.002239+00:00: manual__2024-09-09T18:23:36.002239+00:00, state:running, queued_at: 2024-09-09 18:23:36.009381+00:00. externally triggered: True>
[2024-09-10T11:57:00.576+0800] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2024-09-10T11:57:00.576+0800] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=casia-hwdb_elt, task_id=download_casia-hwdb_1, run_id=manual__2024-09-09T18:23:36.002239+00:00, execution_date=20240909T182336, start_date=20240909T185315, end_date=20240910T035700
[2024-09-10T11:57:00.584+0800] {taskinstance.py:340} INFO - ::group::Post task execution logs
