[2024-09-10T02:29:32.059+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-10T02:29:32.063+0800] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: casia-hwdb_elt.download_casia-hwdb_0 manual__2024-09-09T18:23:36.002239+00:00 [queued]>
[2024-09-10T02:29:32.065+0800] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: casia-hwdb_elt.download_casia-hwdb_0 manual__2024-09-09T18:23:36.002239+00:00 [queued]>
[2024-09-10T02:29:32.065+0800] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2024-09-10T02:29:32.070+0800] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): download_casia-hwdb_0> on 2024-09-09 18:23:36.002239+00:00
[2024-09-10T02:29:32.076+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'casia-hwdb_elt', 'download_casia-hwdb_0', 'manual__2024-09-09T18:23:36.002239+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/var/folders/3n/sh024_795c590k086c59jsw00000gn/T/tmp8vz3puzh']
[2024-09-10T02:29:32.076+0800] {logging_mixin.py:190} WARNING - /Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=72049) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-10T02:29:32.077+0800] {standard_task_runner.py:72} INFO - Started process 72050 to run task
[2024-09-10T02:29:32.077+0800] {standard_task_runner.py:105} INFO - Job 55: Subtask download_casia-hwdb_0
[2024-09-10T02:29:32.091+0800] {task_command.py:467} INFO - Running <TaskInstance: casia-hwdb_elt.download_casia-hwdb_0 manual__2024-09-09T18:23:36.002239+00:00 [running]> on host chens-macbook-pro.local
[2024-09-10T02:29:32.114+0800] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='casia-hwdb_elt' AIRFLOW_CTX_TASK_ID='download_casia-hwdb_0' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T18:23:36.002239+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-09T18:23:36.002239+00:00'
[2024-09-10T02:29:32.116+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-10T02:29:32.117+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-10T02:29:32.118+0800] {logging_mixin.py:190} INFO - Current task name:download_casia-hwdb_0 state:running start_date:2024-09-09 18:29:32.063495+00:00
[2024-09-10T02:29:32.119+0800] {logging_mixin.py:190} INFO - Dag name:casia-hwdb_elt and current dag run status:running
[2024-09-10T02:29:32.119+0800] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-10T02:29:32.184+0800] {s3.py:36} ERROR - Error checking s3://if-letters-home-could-sing/data/casia-hwdb_0.zip: An error occurred (403) when calling the HeadObject operation: Forbidden
[2024-09-10T02:29:32.186+0800] {baseoperator.py:405} WARNING - DownloadOperator.execute cannot be called outside TaskInstance!
[2024-09-10T02:29:32.237+0800] {logging_mixin.py:190} INFO - Error updating job state: An error occurred (UnrecognizedClientException) when calling the UpdateItem operation: The security token included in the request is invalid.
[2024-09-10T02:29:32.256+0800] {s3.py:36} ERROR - Error checking s3://if-letters-home-could-sing/data/casia-hwdb_0.zip: An error occurred (403) when calling the HeadObject operation: Forbidden
[2024-09-10T02:53:10.855+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-10T02:53:10.877+0800] {process_utils.py:132} INFO - Sending 15 to group 72050. PIDs of all processes in the group: [72050]
[2024-09-10T02:53:10.877+0800] {process_utils.py:87} INFO - Sending the signal 15 to group 72050
[2024-09-10T02:53:10.878+0800] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-10T02:53:10.920+0800] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/code/erniesg/if-letters-home-could-sing/pipeline/dags/elt.py", line 51, in process_download
    result = download_op.execute(kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/code/erniesg/if-letters-home-could-sing/pipeline/operators/download.py", line 36, in execute
    self.download_from_url()
  File "/Users/erniesg/code/erniesg/if-letters-home-could-sing/pipeline/operators/download.py", line 53, in download_from_url
    response = requests.get(self.source['path'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/requests/sessions.py", line 746, in send
    r.content
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/requests/models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/urllib3/response.py", line 1060, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/urllib3/response.py", line 949, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/urllib3/response.py", line 873, in _raw_read
    data = self._fp_read(amt, read1=read1) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/urllib3/response.py", line 856, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/lib/python3.12/http/client.py", line 479, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/lib/python3.12/ssl.py", line 1252, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/lib/python3.12/ssl.py", line 1104, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-09-10T02:53:10.927+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-10T02:53:10.928+0800] {logging_mixin.py:190} INFO - Task start:2024-09-09 18:29:32.063495+00:00 end:2024-09-09 18:53:10.927773+00:00 duration:1418.864278
[2024-09-10T02:53:10.928+0800] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): download_casia-hwdb_0> dag:<DAG: casia-hwdb_elt> dagrun:<DagRun casia-hwdb_elt @ 2024-09-09 18:23:36.002239+00:00: manual__2024-09-09T18:23:36.002239+00:00, state:running, queued_at: 2024-09-09 18:23:36.009381+00:00. externally triggered: True>
[2024-09-10T02:53:10.928+0800] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2024-09-10T02:53:10.928+0800] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=casia-hwdb_elt, task_id=download_casia-hwdb_0, run_id=manual__2024-09-09T18:23:36.002239+00:00, execution_date=20240909T182336, start_date=20240909T182932, end_date=20240909T185310
[2024-09-10T02:53:10.932+0800] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-10T02:53:10.937+0800] {process_utils.py:80} INFO - Process psutil.Process(pid=72050, status='terminated', exitcode=2, started='02:29:32') (72050) terminated with exit code 2
[2024-09-10T02:53:13.650+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-10T02:53:13.654+0800] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: casia-hwdb_elt.download_casia-hwdb_0 manual__2024-09-09T18:23:36.002239+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-09-09T18:53:13.654041+00:00 and task will be retried at 2024-09-09T18:54:10.927773+00:00.
[2024-09-10T02:53:13.654+0800] {local_task_job_runner.py:166} INFO - Task is not able to be run
