[2024-09-10T01:59:59.610+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-10T01:59:59.614+0800] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: casia-hwdb_elt.download_casia-hwdb_1 manual__2024-09-09T17:59:34.080448+00:00 [queued]>
[2024-09-10T01:59:59.616+0800] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: casia-hwdb_elt.download_casia-hwdb_1 manual__2024-09-09T17:59:34.080448+00:00 [queued]>
[2024-09-10T01:59:59.616+0800] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2024-09-10T01:59:59.620+0800] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): download_casia-hwdb_1> on 2024-09-09 17:59:34.080448+00:00
[2024-09-10T01:59:59.627+0800] {logging_mixin.py:190} WARNING - /Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=67563) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-10T01:59:59.627+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'casia-hwdb_elt', 'download_casia-hwdb_1', 'manual__2024-09-09T17:59:34.080448+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/var/folders/3n/sh024_795c590k086c59jsw00000gn/T/tmpkp5mfb5h']
[2024-09-10T01:59:59.628+0800] {standard_task_runner.py:72} INFO - Started process 67566 to run task
[2024-09-10T01:59:59.628+0800] {standard_task_runner.py:105} INFO - Job 18: Subtask download_casia-hwdb_1
[2024-09-10T01:59:59.644+0800] {task_command.py:467} INFO - Running <TaskInstance: casia-hwdb_elt.download_casia-hwdb_1 manual__2024-09-09T17:59:34.080448+00:00 [running]> on host chens-macbook-pro.local
[2024-09-10T01:59:59.664+0800] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='casia-hwdb_elt' AIRFLOW_CTX_TASK_ID='download_casia-hwdb_1' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T17:59:34.080448+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-09T17:59:34.080448+00:00'
[2024-09-10T01:59:59.664+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-10T01:59:59.664+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-10T01:59:59.665+0800] {logging_mixin.py:190} INFO - Current task name:download_casia-hwdb_1 state:running start_date:2024-09-09 17:59:59.614469+00:00
[2024-09-10T01:59:59.665+0800] {logging_mixin.py:190} INFO - Dag name:casia-hwdb_elt and current dag run status:running
[2024-09-10T01:59:59.665+0800] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-10T01:59:59.665+0800] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: create_dataset_dag.<locals>.process_download() missing 1 required positional argument: 'job_id'
[2024-09-10T01:59:59.668+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-10T01:59:59.668+0800] {logging_mixin.py:190} INFO - Task start:2024-09-09 17:59:59.614469+00:00 end:2024-09-09 17:59:59.668168+00:00 duration:0.053699
[2024-09-10T01:59:59.668+0800] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): download_casia-hwdb_1> dag:<DAG: casia-hwdb_elt> dagrun:<DagRun casia-hwdb_elt @ 2024-09-09 17:59:34.080448+00:00: manual__2024-09-09T17:59:34.080448+00:00, state:running, queued_at: 2024-09-09 17:59:34.086593+00:00. externally triggered: True>
[2024-09-10T01:59:59.668+0800] {logging_mixin.py:190} INFO - Failure caused by create_dataset_dag.<locals>.process_download() missing 1 required positional argument: 'job_id'
[2024-09-10T01:59:59.669+0800] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=casia-hwdb_elt, task_id=download_casia-hwdb_1, run_id=manual__2024-09-09T17:59:34.080448+00:00, execution_date=20240909T175934, start_date=20240909T175959, end_date=20240909T175959
[2024-09-10T01:59:59.672+0800] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-10T01:59:59.672+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task download_casia-hwdb_1 (create_dataset_dag.<locals>.process_download() missing 1 required positional argument: 'job_id'; 67566)
Traceback (most recent call last):
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: create_dataset_dag.<locals>.process_download() missing 1 required positional argument: 'job_id'
[2024-09-10T01:59:59.692+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-10T01:59:59.700+0800] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-10T01:59:59.700+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
